'''
Created on Feb 14, 2013

@author: jifeng
'''

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPA_input4.ui'
#
# Created: Thu Feb 14 13:40:07 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import  QCompleter, QStringListModel
import CPA
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(1080, 747)
        self.formLayout = QtGui.QFormLayout(Dialog)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.input_filename = QtGui.QLineEdit(Dialog)
        self.input_filename.setObjectName(_fromUtf8("input_filename"))
        self.gridLayout_6.addWidget(self.input_filename, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.pushButton_input = QtGui.QPushButton(Dialog)
        self.pushButton_input.setEnabled(True)
        self.pushButton_input.setObjectName(_fromUtf8("pushButton_input"))
        self.gridLayout_6.addWidget(self.pushButton_input, 1, 2, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.gridLayout_6)
        self.length = QtGui.QGroupBox(Dialog)
        self.length.setEnabled(True)
        self.length.setObjectName(_fromUtf8("length"))
        self.gridLayout = QtGui.QGridLayout(self.length)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.length)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.max_70 = QtGui.QLineEdit(self.length)
        self.max_70.setEnabled(True)
        self.max_70.setObjectName(_fromUtf8("max_70"))
        self.gridLayout.addWidget(self.max_70, 3, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.length)
        self.label_16.setEnabled(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 2, 1, 1)
        self.max_5 = QtGui.QLineEdit(self.length)
        self.max_5.setEnabled(True)
        self.max_5.setObjectName(_fromUtf8("max_5"))
        self.gridLayout.addWidget(self.max_5, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.length)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.primer_length_max = QtGui.QLineEdit(self.length)
        self.primer_length_max.setEnabled(True)
        self.primer_length_max.setObjectName(_fromUtf8("primer_length_max"))
        self.gridLayout.addWidget(self.primer_length_max, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.length)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.min_30 = QtGui.QLineEdit(self.length)
        self.min_30.setEnabled(True)
        self.min_30.setObjectName(_fromUtf8("min_30"))
        self.gridLayout.addWidget(self.min_30, 3, 0, 1, 1)
        self.primer_length_min = QtGui.QLineEdit(self.length)
        self.primer_length_min.setEnabled(True)
        self.primer_length_min.setObjectName(_fromUtf8("primer_length_min"))
        self.gridLayout.addWidget(self.primer_length_min, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.length)
        self.label_15.setEnabled(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.length)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.Mg = QtGui.QLineEdit(self.groupBox_2)
        self.Mg.setEnabled(True)
        self.Mg.setObjectName(_fromUtf8("Mg"))
        self.gridLayout_5.addWidget(self.Mg, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.oligo = QtGui.QLineEdit(self.groupBox_2)
        self.oligo.setEnabled(True)
        self.oligo.setObjectName(_fromUtf8("oligo"))
        self.gridLayout_5.addWidget(self.oligo, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setEnabled(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 3, 1, 1)
        self.dNTP = QtGui.QLineEdit(self.groupBox_2)
        self.dNTP.setObjectName(_fromUtf8("dNTP"))
        self.gridLayout_5.addWidget(self.dNTP, 1, 3, 1, 1)
        self.salt = QtGui.QLineEdit(self.groupBox_2)
        self.salt.setEnabled(True)
        self.salt.setObjectName(_fromUtf8("salt"))
        self.gridLayout_5.addWidget(self.salt, 1, 0, 1, 1)
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.groupBox_2)
        self.bool_conservation = QtGui.QCheckBox(Dialog)
        self.bool_conservation.setEnabled(True)
        self.bool_conservation.setObjectName(_fromUtf8("bool_conservation"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.bool_conservation)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.label_19)
        self.snp_fname = QtGui.QLineEdit(Dialog)
        self.snp_fname.setEnabled(False)
        self.snp_fname.setObjectName(_fromUtf8("snp_fname"))
        self.horizontalLayout_2.addWidget(self.snp_fname)
        self.pushButton_snpfile = QtGui.QPushButton(Dialog)
        self.pushButton_snpfile.setEnabled(False)
        self.pushButton_snpfile.setObjectName(_fromUtf8("pushButton_snpfile"))
        self.horizontalLayout_2.addWidget(self.pushButton_snpfile)
        self.formLayout.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.maxTm = QtGui.QLineEdit(self.groupBox_3)
        self.maxTm.setEnabled(True)
        self.maxTm.setObjectName(_fromUtf8("maxTm"))
        self.gridLayout_4.addWidget(self.maxTm, 1, 1, 1, 1)
        self.minTm = QtGui.QLineEdit(self.groupBox_3)
        self.minTm.setEnabled(True)
        self.minTm.setObjectName(_fromUtf8("minTm"))
        self.gridLayout_4.addWidget(self.minTm, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setEnabled(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 4, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setEnabled(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 0, 1, 1, 1)
        self.maxDG5 = QtGui.QLineEdit(self.groupBox_3)
        self.maxDG5.setEnabled(True)
        self.maxDG5.setObjectName(_fromUtf8("maxDG5"))
        self.gridLayout_4.addWidget(self.maxDG5, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setEnabled(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.max_snp = QtGui.QLineEdit(self.groupBox_3)
        self.max_snp.setEnabled(False)
        self.max_snp.setObjectName(_fromUtf8("max_snp"))
        self.gridLayout_4.addWidget(self.max_snp, 1, 5, 1, 1)
        self.hairpin = QtGui.QLineEdit(self.groupBox_3)
        self.hairpin.setEnabled(True)
        self.hairpin.setObjectName(_fromUtf8("hairpin"))
        self.gridLayout_4.addWidget(self.hairpin, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 2, 1, 1)
        self.self_dimer = QtGui.QLineEdit(self.groupBox_3)
        self.self_dimer.setEnabled(True)
        self.self_dimer.setObjectName(_fromUtf8("self_dimer"))
        self.gridLayout_4.addWidget(self.self_dimer, 1, 3, 1, 1)
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.groupBox_3)
        self.no_cross_check_radio = QtGui.QRadioButton(Dialog)
        self.no_cross_check_radio.setChecked(True)
        self.no_cross_check_radio.setObjectName(_fromUtf8("no_cross_check_radio"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.no_cross_check_radio)
        self.human_cross_check_radio = QtGui.QRadioButton(Dialog)
        self.human_cross_check_radio.setObjectName(_fromUtf8("human_cross_check_radio"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.human_cross_check_radio)
        self.customer_cross_check_radio = QtGui.QRadioButton(Dialog)
        self.customer_cross_check_radio.setObjectName(_fromUtf8("customer_cross_check_radio"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.customer_cross_check_radio)

        self.input_organ = QtGui.QLineEdit(Dialog)
        self.input_organ.setEnabled(False)
        self.input_organ.setObjectName(_fromUtf8("input_organ"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.input_organ)
        completer = QCompleter()
        self.input_organ.setCompleter(completer)
        model = QStringListModel()
        completer.setModel(model)
        completer.setModelSorting(QCompleter.CaseInsensitivelySortedModel)
        CPA.get_data(model)
        
        self.input_organ2 = QtGui.QLineEdit(Dialog)
        self.input_organ2.setEnabled(False)
        self.input_organ2.setObjectName(_fromUtf8("input_organ2"))
        self.formLayout.setWidget(19, QtGui.QFormLayout.FieldRole, self.input_organ2)
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setEnabled(True)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(23, QtGui.QFormLayout.LabelRole, self.label_21)
        self.max_human = QtGui.QLineEdit(Dialog)
        self.max_human.setEnabled(False)
        self.max_human.setObjectName(_fromUtf8("max_human"))
        self.formLayout.setWidget(23, QtGui.QFormLayout.FieldRole, self.max_human)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.set_max_snp = QtGui.QLineEdit(self.groupBox_4)
        self.set_max_snp.setEnabled(False)
        self.set_max_snp.setObjectName(_fromUtf8("set_max_snp"))
        self.gridLayout_3.addWidget(self.set_max_snp, 1, 0, 1, 1)
        self.cross_dimer = QtGui.QLineEdit(self.groupBox_4)
        self.cross_dimer.setEnabled(True)
        self.cross_dimer.setObjectName(_fromUtf8("cross_dimer"))
        self.gridLayout_3.addWidget(self.cross_dimer, 1, 1, 1, 1)
        self.set_max_human = QtGui.QLineEdit(self.groupBox_4)
        self.set_max_human.setEnabled(False)
        self.set_max_human.setObjectName(_fromUtf8("set_max_human"))
        self.gridLayout_3.addWidget(self.set_max_human, 1, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setEnabled(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 0, 1, 1, 1)
        self.formLayout.setWidget(24, QtGui.QFormLayout.SpanningRole, self.groupBox_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_20 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_4.addWidget(self.label_20)
        self.output_fname = QtGui.QLineEdit(Dialog)
        self.output_fname.setObjectName(_fromUtf8("output_fname"))
        self.horizontalLayout_4.addWidget(self.output_fname)
        self.pushButton_output = QtGui.QPushButton(Dialog)
        self.pushButton_output.setEnabled(True)
        self.pushButton_output.setObjectName(_fromUtf8("pushButton_output"))
        self.horizontalLayout_4.addWidget(self.pushButton_output)
        self.formLayout.setLayout(26, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_help = QtGui.QPushButton(Dialog)
        self.pushButton_help.setEnabled(True)
        self.pushButton_help.setObjectName(_fromUtf8("pushButton_help"))
        self.horizontalLayout.addWidget(self.pushButton_help)
        self.buttonBox_gui = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_gui.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_gui.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_gui.setObjectName(_fromUtf8("buttonBox_gui"))
        self.horizontalLayout.addWidget(self.buttonBox_gui)
        self.formLayout.setLayout(27, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.add_button = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.add_button)
        self.label_19.setBuddy(self.snp_fname)
        self.label_11.setBuddy(self.max_snp)
        self.label_21.setBuddy(self.max_human)
        self.label_13.setBuddy(self.set_max_snp)
        self.label_22.setBuddy(self.set_max_human)


        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_gui, QtCore.SIGNAL(_fromUtf8("accepted()")), self.submit)
        QtCore.QObject.connect(self.buttonBox_gui, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_19.setEnabled)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.snp_fname.setEnabled)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButton_snpfile.setEnabled)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.max_snp.setEnabled)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_13.setEnabled)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.set_max_snp.setEnabled)
        QtCore.QObject.connect(self.bool_conservation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_11.setEnabled)
        QtCore.QObject.connect(Dialog, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.hide)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ.setDisabled)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ2.setDisabled)
        QtCore.QObject.connect(self.human_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.max_human.setEnabled)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.max_human.setDisabled)
        QtCore.QObject.connect(self.no_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ.setDisabled)
        QtCore.QObject.connect(self.no_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ2.setDisabled)
        QtCore.QObject.connect(self.no_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.max_human.setDisabled)
        QtCore.QObject.connect(self.human_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ.setDisabled)
        QtCore.QObject.connect(self.human_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ2.setDisabled)
        QtCore.QObject.connect(self.human_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.max_human.setEnabled)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ.setEnabled)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.max_human.setEnabled)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Dialog.setEnabled)
        QtCore.QObject.connect(self.customer_cross_check_radio, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.input_organ2.setEnabled)

        QtCore.QObject.connect(self.add_button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.add_taxid) # to add taxid to the exclusion list
        QtCore.QObject.connect(self.pushButton_input, QtCore.SIGNAL("clicked()"), self.filebrower_input) #for input file
        QtCore.QObject.connect(self.pushButton_output, QtCore.SIGNAL("clicked()"), self.filebrower_output) #for ouput file
        QtCore.QObject.connect(self.pushButton_snpfile, QtCore.SIGNAL("clicked()"), self.filebrower_snpfile) #for bioedit file
        QtCore.QObject.connect(self.pushButton_help, QtCore.SIGNAL("clicked()"), self.filebrower_help) #for help file
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_14.setText(_translate("Dialog", "Input Sequence", None))
        self.pushButton_input.setText(_translate("Dialog", "Brower...", None))
        self.length.setTitle(_translate("Dialog", "Length", None))
        self.label.setText(_translate("Dialog", "Minimum primer length", None))
        self.max_70.setText(_translate("Dialog", "70", None))
        self.label_16.setText(_translate("Dialog", "Maximum  distance between 2nd and 3rd primers", None))
        self.max_5.setText(_translate("Dialog", "5", None))
        self.label_2.setText(_translate("Dialog", "Maximum distance between 1st and 2nd primers, 3rd and 4th primers", None))
        self.primer_length_max.setText(_translate("Dialog", "25", None))
        self.label_3.setText(_translate("Dialog", "Maximum primer length", None))
        self.min_30.setText(_translate("Dialog", "30", None))
        self.primer_length_min.setText(_translate("Dialog", "20", None))
        self.label_15.setText(_translate("Dialog", "Minimum  distance between 2nd and 3rd primers", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Concentration", None))
        self.Mg.setText(_translate("Dialog", "3", None))
        self.label_5.setText(_translate("Dialog", "Mg(mM)", None))
        self.label_4.setText(_translate("Dialog", "Salt (mM)", None))
        self.oligo.setText(_translate("Dialog", "250", None))
        self.label_6.setText(_translate("Dialog", "Oligo(nM)", None))
        self.label_7.setText(_translate("Dialog", "dNTP(mM)", None))
        self.dNTP.setText(_translate("Dialog", "0.00008", None))
        self.salt.setText(_translate("Dialog", "50", None))
        self.bool_conservation.setText(_translate("Dialog", "Conservation check", None))
        self.label_19.setText(_translate("Dialog", "Bioedit file", None))
        self.pushButton_snpfile.setText(_translate("Dialog", "Brower...", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Individual Primer requirements", None))
        self.maxTm.setText(_translate("Dialog", "65", None))
        self.minTm.setText(_translate("Dialog", "60", None))
        self.label_11.setText(_translate("Dialog", "Maximum SNP", None))
        self.label_10.setText(_translate("Dialog", "Self Dimer", None))
        self.label_23.setText(_translate("Dialog", "Hairpin", None))
        self.label_18.setText(_translate("Dialog", "Maximum Tm", None))
        self.maxDG5.setText(_translate("Dialog", "-3", None))
        self.label_17.setText(_translate("Dialog", "Minimum Tm", None))
        self.max_snp.setText(_translate("Dialog", "1", None))
        self.hairpin.setText(_translate("Dialog", "3", None))
        self.label_8.setText(_translate("Dialog", "Max 3\'  Stability", None))
        self.self_dimer.setText(_translate("Dialog", "5", None))
        self.no_cross_check_radio.setText(_translate("Dialog", "No cross-reaction check", None))
        self.human_cross_check_radio.setText(_translate("Dialog", "Human crossreaction check", None))
        self.customer_cross_check_radio.setText(_translate("Dialog", "customized  exclusion organism", None))
        self.label_21.setText(_translate("Dialog", "Maximum allowed consecutive match ", None))
        self.max_human.setText(_translate("Dialog", "20", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Primer set requirements", None))
        self.label_13.setText(_translate("Dialog", "Maximum sum of snp", None))
        self.set_max_snp.setText(_translate("Dialog", "3", None))
        self.cross_dimer.setText(_translate("Dialog", "5", None))
        self.set_max_human.setText(_translate("Dialog", "1", None))
        self.label_22.setText(_translate("Dialog", "Number of cross-reaction primer allowed ", None))
        self.label_25.setText(_translate("Dialog", "Max Cross Dimer", None))
        self.label_20.setText(_translate("Dialog", "Output Result", None))
        self.pushButton_output.setText(_translate("Dialog", "Brower...", None))
        self.pushButton_help.setText(_translate("Dialog", "Help", None))
        self.add_button.setText(_translate("Dialog", "+", None))


    def add_taxid(self): # this is for add one new taxid to the exclusion list
            mid=" OR "
            if  self.input_organ2.text()=="":
                self.input_organ2.setText(self.input_organ.text())
            else:
                self.input_organ2.setText(self.input_organ.text()+mid+self.input_organ.text())
            self.input_organ.setText("")
    def submit(self):
        #CPA.CPA(self.input_filename.text(),self.primer_length_min.text(), self.primer_length_max.text(),self.max_5.text(),self.min_30.text(),self.max_70.text(),self.salt.text(),self.Mg.text(),self.oligo.text(),self.dNTP.text(),self.minTm.text(),self.maxTm.text(),self.maxDG5.text(),                                                                                                    self.bool_conservation.isChecked(),self.snp_fname.text(),self.bool_human.isChecked(),self.max_human.text(),self.set_max_snp.text(),self.set_maxDG3.text(),self.set_maxDG.text(),self.set_max_human.text(),self.output_fname.text())
        CPA.CPA_run(str(self.input_filename.text()),str(self.snp_fname.text()),int(self.primer_length_min.text()), int(self.primer_length_max.text()),int(self.max_5.text()),int(self.min_30.text()),int(self.max_70.text()),float(self.salt.text()),float(self.Mg.text()),float(self.oligo.text()),float(self.dNTP.text()),float(self.minTm.text()),float(self.maxTm.text()),float(self.maxDG5.text()),self.bool_conservation.isChecked(),int(self.max_snp.text()),int(self.set_max_snp.text()),self.human_cross_check_radio.isChecked(),self.customer_cross_check_radio.isChecked(),str(self.input_organ2.text()), int(self.max_human.text()),int(self.set_max_human.text()),str(self.output_fname.text()),int(self.self_dimer.text()),int(self.hairpin.text()),int(self.cross_dimer.text()))

    def filebrower_input(self):
        fname = QtGui.QFileDialog.getOpenFileName(Dialog, "Open file", ".",)
        self.input_filename.setText(fname)

    def filebrower_output(self):
        fname = QtGui.QFileDialog.getSaveFileName(Dialog, "Save as excel file", "Save results as new file", Dialog.tr("txt Files (*.xls)"))
        self.output_fname.setText(fname)

    def filebrower_snpfile(self):
        fname = QtGui.QFileDialog.getOpenFileName(Dialog, "Open file", ".",)
        self.snp_fname.setText(fname)

    def filebrower_help(self):
        print "help"



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

